Repository s0lvang/Karantenehjelpen, pull requests merged in 2020-03, with the labels that each got.

#51 SMS og .env
  package.json
  src/components/CreateRequest.vue
  src/components/DetailedRequest.vue
  src/components/Map.vue
  src/firebaseConfig.js
  src/services/fetchLocations.js
  src/services/sms.js
  src/views/Login.vue
  src/views/RequestView.vue
Labels: enhancement

#54 Build and lint with Github Actions
  .github/workflows/nodejs.yml
  package-lock.json
Labels: enhancement

#73 La personen som leverer notifye brukeren om at han/hun har levert
  karantenehjelpen.code-workspace
  src/views/RequestView.vue
Labels: enhancement

#74 Åpne veiviser til addresse når man klikker på addresse
  src/components/DetailedRequest.vue
Labels: enhancement

#128 Bedre håndtering av nye varer i handlekurv
  src/components/CreateEditRequest.vue
  src/components/shared/Items.vue
Labels: enhancement

#140 Send kunden direkte til ordren når de blir bedt om å bekrefte leveransen
  src/views/RequestView.vue
Labels: enhancement

#147 Bruk date-fns for å formattere tid
  package-lock.json
  package.json
  src/helpers/datetime.js
Labels: enhancement

#129 Legge til epost og passord som et innloggingsalternativ
  src/components/GoogleLoginButton.vue
  src/components/LoginArea.vue
  src/components/shared/Button.vue
  src/components/shared/TextInput.vue
  src/helpers/auth.js
  src/views/Login.vue
Labels: enhancement

#127 Kart med alle oppdrag
  src/components/AllRequestsMap.vue
  src/components/Menu.vue
  src/views/AllRequests.vue
Labels: enhancement

#164 Word-break og lintfixes
  src/common/base.scss
  src/components/LoginArea.vue
  src/helpers/auth.js
Labels: Enhancement

#165 Bytt placeholdernummer til 00000000
  src/views/MyPageView.vue
Labels: Enhancement

#166 Oppdater readme slik at det er lettere å bidra/forstå hva prosjektet er
  .env_example
  CONTRIBUTING.md
  README.md
  src/assets/startside.jpg
Labels: documentation
